API/urls.py
from django.conf.urls import include, url
from .views import TicketViewSet, TicketPriorityViewSet, TicketProblemViewSet,\
    ticket_list, ticket_create, get_ticket, answer_ticket, reply_ticket,\
    close_ticket, closed_ticket_list, pending_ticket_list, load_user, save_user
from rest_framework.routers import SimpleRouter

router = SimpleRouter()
router.register(r'tickets', TicketViewSet)
router.register(r'ticket_priorities', TicketPriorityViewSet)
router.register(r'ticket_problems', TicketProblemViewSet)

urlpatterns = [
    url(r'^ticket_list/$', ticket_list, name='ticket_list'),
    url(r'^pending_ticket_list/$', pending_ticket_list, name='pending_ticket_list'),
    url(r'^closed_ticket_list/$', closed_ticket_list, name='closed_ticket_list'),
    url(r'^ticket_create/$', ticket_create, name='ticket_create'),
    url(r'^get_ticket/$', get_ticket, name='get_ticket'),
    url(r'^answer_ticket/$', answer_ticket, name='answer_ticket'),
    url(r'^reply_ticket/$', reply_ticket, name='reply_ticket'),
    url(r'^close_ticket/$', close_ticket, name='close_ticket'),
    url(r'^load_user/$', load_user, name='load_user'),
    url(r'^save_user/$', save_user, name='save_user'),
    url(r'^', include(router.urls)),
]

Client/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.customer),
    url(r'^agent/$', views.agent),
]

TicketSystem/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from rest_framework.authtoken import views as rest_framework_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include('API.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^api/get_auth_token/$', rest_framework_views.obtain_auth_token, name='get_auth_token'),
    url(r'^', include('Client.urls')),
]

API/models.py
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)


class TicketPriority(models.Model):

    class Meta:
        verbose_name_plural = 'Ticket priorities'
        ordering = ["order"]

    name = models.CharField(max_length=50)
    value = models.CharField(max_length=20)
    order = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.name


class TicketProblem(models.Model):

    class Meta:
        ordering = ["order"]

    name = models.CharField(max_length=50)
    value = models.CharField(max_length=20)
    order = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.name


class TicketStatus(models.Model):

    class Meta:
        verbose_name_plural = 'Ticket statuses'
        ordering = ["order"]

    name = models.CharField(max_length=50)
    value = models.CharField(max_length=20)
    order = models.IntegerField(null=True, blank=True)

    def __str__(self):
        return self.name


class Ticket(models.Model):

    created_by = models.ForeignKey(
        User, related_name='ticket_created_by', verbose_name='Created by')
    created_date = models.DateTimeField("Created date", auto_now_add=True)
    order_number = models.CharField("Order reference No", max_length=50)
    priority = models.ForeignKey(TicketPriority, verbose_name='Ticket priority')
    problem = models.ForeignKey(
        TicketProblem, verbose_name='I\'m having a problem with')
    description = models.TextField("Describe your problem")
    status = models.ForeignKey(
        TicketStatus, verbose_name='Ticket status', default=1)
    assigned_to = models.ForeignKey(
        User, related_name='ticket_assigned_to', verbose_name='Assigend to',
        null=True, blank=True)
    closed_date = models.DateTimeField("Closed", null=True, blank=True)

    def __str__(self):
        return self.problem.name + ': ' + self.description[0:40].strip()


class TicketItem():

    def __init__(self, id, order, created, closed, created_by, priority, problem, description, status, agent):
        self.id = id
        self.order = order
        self.created = created
        self.closed = closed
        self.created_by = created_by
        self.priority = priority
        self.problem = problem
        self.description = description
        self.status = status
        self.agent = agent

Client/models.py
from django.db import models

# Create your models here.

Client/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse


def customer(request):
    context = {}
    return render(request, 'Client/customer.html', context)


def agent(request):
    context = {}
    return render(request, 'Client/agent.html', context)

Client/templates/Client/agent.html
{% extends "Client/base.html" %}
{% load static %}

{% block menu %}
    <li>
        <a href="javascript:void(0)" onclick="show_section('1')"><i class="fa fa-list fa-fw"></i> Pending requests</a>
    </li>
    <li>
        <a href="javascript:void(0)" onclick="show_section('2')"><i class="fa fa-check-circle fa-fw"></i> Closed requests</a>
    </li>
    <li>
        <a href="javascript:void(0)" onclick="show_section('3')"><i class="fa fa-user fa-fw"></i> User settings</a>
    </li>
    <li>
        <a href="javascript:void(0)" onclick="logout()"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
    </li>
{% endblock %}

{% block title %}Support Agent{% endblock %}
{% block portal %}Support Agent{% endblock %}

{% block content %}
    <div id="section-1" style="display:none">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Pending requests</h1>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <table id="main-table" class="table table-striped table-bordered" cellspacing="0" width="100%">
                            <thead>
                                <tr>
                                    <th>Action</th>
                                    <th>Order</th>
                                    <th>Created</th>
                                    <th>Priority</th>
                                    <th>Problem</th>
                                    <th>Status</th>
                                    <th>Agent</th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="section-2" style="display:none">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Closed requests</h1>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <table id="closed-table" class="table table-striped table-bordered" cellspacing="0" width="100%">
                            <thead>
                                <tr>
                                    <th>Action</th>
                                    <th>Order</th>
                                    <th>Created</th>
                                    <th>Priority</th>
                                    <th>Problem</th>
                                    <th>Status</th>
                                    <th>Agent</th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="section-3" style="display:none">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">User settings</h1>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-3"></div>
            <div class="col-lg-6">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <form action="{{ request.path }}" method="post" id="form-updateuser" role="form">
                            <div class="form-body">
                                <div class="form-group">
                                    <label for="id_name">First name</label>
                                    <input class="form-control" id="id_first_name" maxlength="100" name="name" placeholder="First name" type="text" required="">
                                </div>
                                <div class="form-group">
                                    <label for="id_name">Last name</label>
                                    <input class="form-control" id="id_last_name" maxlength="100" name="name" placeholder="Last name" type="text" required="">
                                </div>
                                <div class="form-group">
                                    <label for="id_email">E-mail</label>
                                    <input class="form-control" id="id_email" maxlength="100" name="email" placeholder="E-mail" type="text" required="">
                                </div>
                                <a href="javascript:void(0)" onclick="save_user()" class="btn btn-primary">Update</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-3"></div>
        </div>
    </div>
    <div id="section-4" style="display:none">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Ticket detail</h1>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-4">  
                                <div class="ticket_field"><strong>Created: </strong><span id="ticket_created_date"></span></div>
                                <div class="ticket_field"><strong>Order No: </strong><span id="ticket_order_number"></span></div>
                                <div class="ticket_field"><strong>Closed: </strong><span id="ticket_closed_date"></span></div>
                            </div>
                            <div class="col-lg-4">  
                                <div class="ticket_field"><strong>Customer: </strong><span id="ticket_created_by"></span></div>
                                <div class="ticket_field"><strong>Agent: </strong><span id="ticket_assigned_to"></span></div>
                            </div>
                            <div class="col-lg-4">  
                                <div class="ticket_field"><strong>Priority: </strong><span id="ticket_priority"></span></div>
                                <div class="ticket_field"><strong>Status: </strong><span id="ticket_status"></span></div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="ticket_field"><strong>Problem: </strong><span id="ticket_problem"></span></div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <hr>
                                <span id="ticket_description"></span>
                            </div>
                        </div>
                        <div id="answer-box" style="display:none" class="row">
                            <div class="col-lg-12">
                                <hr>
                                <form action="{{ request.path }}" method="post" id="form-answerrequest" role="form">
                                    <div class="form-body">
                                        <div class="form-group">
                                            <label for="id_description">Answer</label>
                                            <input type="hidden" id="ticket_id" name="id" value="">
                                            <textarea class="form-control" cols="40" id="ticket_answer" name="answer" placeholder="Answer" rows="10"></textarea>
                                        </div>
                                        <a href="javascript:void(0)" onclick="answer_ticket()" class="btn btn-primary">Answer</a>
                                        <a href="javascript:void(0)" onclick="close_ticket()" class="btn btn-success">Close ticket</a>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block extraJS %}
    <script src="{% static 'js/agent.js' %}"></script>
{% endblock %}    

Client/templates/Client/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Tickets System - {% block title %}{% endblock %}</title>

    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/metisMenu/metisMenu.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="{% static 'vendor/datatables/datatables.min.css' %}"/>
    <link href="{% static 'css/sb-admin-2.css' %}" rel="stylesheet">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand">{% block portal %}Customer Support{% endblock %}</a>
            </div>

            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        {% block menu %}{% endblock %}
                    </ul>
                </div>
            </div>
        </nav>

        <div id="page-wrapper">
            <div class="container-fluid">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>

    <div class="modal fade" id="loginModal" tabindex="-1" role="dialog" data-backdrop="static" aria-labelledby="exampleModalLabel">
        <div class="modal-dialog modal-sm" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h4 class="modal-title" id="modalLabel">User Login</h4>
              </div>
              <div class="modal-body">
                <form>
                  <div class="form-group">
                    <input class="form-control" id="id_username" maxlength="254" name="username" type="text" required="" autofocus>
                  </div>
                  <div class="form-group">
                    <input class="form-control" id="id_password" name="password" type="password" required="" autocomplete="off" placeholder="Password">
                  </div>
                </form>
              </div>
              <div class="modal-footer">
                <button type="button" onclick="login()" class="btn btn-primary">Login</button>
              </div>
            </div>
        </div>
    </div>

    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'vendor/metisMenu/metisMenu.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'vendor/datatables/datatables.min.js' %}"></script>
    <script src="{% static 'js/sb-admin-2.js' %}"></script>
    <script src="{% static 'js/common.js' %}"></script>

    {% block extraJS %}
    {% endblock %}    

</body>

</html>

Client/templates/Client/customer.html
{% extends "Client/base.html" %}
{% load static %}

{% block menu %}
    <li>
        <a href="javascript:void(0)" onclick="show_section('1')"><i class="fa fa-list fa-fw"></i> Requests list</a>
    </li>
    <li>
        <a href="javascript:void(0)" onclick="show_section('2')"><i class="fa fa-star fa-fw"></i> Create new request</a>
    </li>
    <li>
        <a href="javascript:void(0)" onclick="show_section('3')"><i class="fa fa-user fa-fw"></i> User settings</a>
    </li>
    <li>
        <a href="javascript:void(0)" onclick="logout()"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
    </li>
{% endblock %}

{% block title %}Customer Support{% endblock %}
{% block portal %}Customer Support{% endblock %}

{% block content %}
    <div id="section-1" style="display:none">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Requests list</h1>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <table id="main-table" class="table table-striped table-bordered" cellspacing="0" width="100%">
                            <thead>
                                <tr>
                                    <th>Action</th>
                                    <th>Order</th>
                                    <th>Created</th>
                                    <th>Priority</th>
                                    <th>Problem</th>
                                    <th>Status</th>
                                    <th>Agent</th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div id="section-2" style="display:none">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Create new request</h1>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-3"></div>
            <div class="col-lg-6">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <form action="{{ request.path }}" method="post" id="form-newrequest" role="form">
                            <div class="form-body">
                                <div class="form-group">
                                    <label for="id_order_number">Order reference No</label>
                                    <input class="form-control" id="id_order_number" maxlength="100" name="order_number" placeholder="Order number" type="text" required="">
                                </div>
                                <div class="form-group">
                                    <label for="id_priority">Ticket priority</label>
                                    <select class="form-control" id="id_priority" name="priority" placeholder="Priority">
                                    </select>        
                                </div>
                                <div class="form-group">
                                    <label for="id_problem">I'm having a problem with</label>
                                    <select class="form-control" id="id_problem" name="problem" placeholder="Problem">
                                    </select>        
                                </div>
                                <div class="form-group">
                                    <label for="id_description">Describe your problem</label>
                                    <textarea class="form-control" cols="40" id="id_description" name="description" placeholder="Description" rows="10"></textarea>
                                </div>
                                <a href="javascript:void(0)" onclick="create_ticket()" class="btn btn-primary">Send</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-3"></div>
        </div>
    </div>
    <div id="section-3" style="display:none">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">User settings</h1>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-3"></div>
            <div class="col-lg-6">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <form action="{{ request.path }}" method="post" id="form-updateuser" role="form">
                            <div class="form-body">
                                <div class="form-group">
                                    <label for="id_name">First name</label>
                                    <input class="form-control" id="id_first_name" maxlength="100" name="name" placeholder="First name" type="text" required="">
                                </div>
                                <div class="form-group">
                                    <label for="id_name">Last name</label>
                                    <input class="form-control" id="id_last_name" maxlength="100" name="name" placeholder="Last name" type="text" required="">
                                </div>
                                <div class="form-group">
                                    <label for="id_email">E-mail</label>
                                    <input class="form-control" id="id_email" maxlength="100" name="email" placeholder="E-mail" type="text" required="">
                                </div>
                                <a href="javascript:void(0)" onclick="save_user()" class="btn btn-primary">Update</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-3"></div>
        </div>
    </div>
    <div id="section-4" style="display:none">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Ticket detail</h1>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-4">  
                                <div class="ticket_field"><strong>Created: </strong><span id="ticket_created_date"></span></div>
                                <div class="ticket_field"><strong>Order No: </strong><span id="ticket_order_number"></span></div>
                                <div class="ticket_field"><strong>Closed: </strong><span id="ticket_closed_date"></span></div>
                            </div>
                            <div class="col-lg-4">  
                                <div class="ticket_field"><strong>Customer: </strong><span id="ticket_created_by"></span></div>
                                <div class="ticket_field"><strong>Agent: </strong><span id="ticket_assigned_to"></span></div>
                            </div>
                            <div class="col-lg-4">  
                                <div class="ticket_field"><strong>Priority: </strong><span id="ticket_priority"></span></div>
                                <div class="ticket_field"><strong>Status: </strong><span id="ticket_status"></span></div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="ticket_field"><strong>Problem: </strong><span id="ticket_problem"></span></div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12">
                                <hr>
                                <span id="ticket_description"></span>
                            </div>
                        </div>
                        <div id="answer-box" style="display:none" class="row">
                            <div class="col-lg-12">
                                <hr>
                                <form action="{{ request.path }}" method="post" id="form-answerrequest" role="form">
                                    <div class="form-body">
                                        <div class="form-group">
                                            <input type="hidden" id="ticket_id" name="id" value="">
                                            <label for="ticket_answer">Reply</label>
                                            <textarea class="form-control" cols="40" id="ticket_answer" name="answer" placeholder="Reply" rows="10"></textarea>
                                        </div>
                                        <a href="javascript:void(0)" onclick="reply_ticket()" class="btn btn-primary">Reply</a>
                                        <a href="javascript:void(0)" onclick="close_ticket()" class="btn btn-success">Close ticket</a>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block extraJS %}
    <script src="{% static 'js/customer.js' %}"></script>
{% endblock %}    